# Generated by Django 6.0.2 on 2026-02-23 13:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_criterion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.criterion')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.option')),
            ],
            options={
                'unique_together': {('option', 'criterion')},
            },
        ),
    ]
